vars:
  # List of random seeds for data split
  - random_seed: [387, 3, 510, 892, 658, 284, 669, 295, 552, 561, 568, 703, 200, 201, 586, 460, 77, 462, 209, 855, 730, 475, 476, 740, 741, 105, 754, 891, 508, 126] 
  - global_options: ""
  - models:
      - mmbert

stages:
  baseline_hpsearch:
    matrix:
      experiment: ${models}
      random_seed: ${random_seed}
    cmd: python hpsearch.py --config experiments/baseline_${item.experiment}.yaml --set dataset_args.random_seed=${item.random_seed} ${global_options}
    deps:
      - datasets/breast_cancer_dataset
      - hpsearch.py
    outs:
      - experiments/baseline_${item.experiment}/hpsearch_eval_loss_data_split_seed_${item.random_seed}.jsonl

  baseline:
    matrix:
      experiment: ${models}
      random_seed: ${random_seed}
    cmd: python train.py --config experiments/baseline_${item.experiment}.yaml --set dataset_args.random_seed=${item.random_seed} ${global_options}
    deps:
      - experiments/baseline_${item.experiment}/hpsearch_eval_loss_data_split_seed_${item.random_seed}.jsonl
      - datasets/breast_cancer_dataset
    outs:
      - experiments/baseline_${item.experiment}/metrics_data_split_seed_${item.random_seed}.jsonl

  exp_1_mecla_hpsearch:
    matrix:
      experiment: ${models}
      random_seed: ${random_seed}
    cmd: python hpsearch.py --config experiments/exp_1_mecla_${item.experiment}.yaml --set dataset_args.random_seed=${item.random_seed}  ${global_options}
    deps:
      - datasets/breast_cancer_dataset
    outs:
      - experiments/exp_1_mecla_${item.experiment}/hpsearch_eval_loss_data_split_seed_${item.random_seed}.jsonl

  exp_1_mecla:
    matrix:
      experiment: ${models}
      random_seed: ${random_seed}
    cmd: python train.py --config experiments/exp_1_mecla_${item.experiment}.yaml --set dataset_args.random_seed=${item.random_seed} ${global_options}
    deps:
      - experiments/baseline_${item.experiment}/hpsearch_eval_loss_data_split_seed_${item.random_seed}.jsonl
      - experiments/exp_1_mecla_${item.experiment}/hpsearch_eval_loss_data_split_seed_${item.random_seed}.jsonl
      - datasets/breast_cancer_dataset
    outs:
      - experiments/exp_1_mecla_${item.experiment}/metrics_data_split_seed_${item.random_seed}.jsonl

  exp_2_mecla_hpsearch:
    matrix:
      experiment: ${models}
      random_seed: ${random_seed}
    cmd: python hpsearch.py --config experiments/exp_2_mecla_${item.experiment}.yaml --set dataset_args.random_seed=${item.random_seed} ${global_options}
    deps:
      - datasets/breast_cancer_dataset
    outs:
      - experiments/exp_2_mecla_${item.experiment}/hpsearch_eval_loss_data_split_seed_${item.random_seed}.jsonl

  exp_2_mecla:
    matrix:
      experiment: ${models}
      random_seed: ${random_seed}
    cmd: python train.py --config experiments/exp_2_mecla_${item.experiment}.yaml --set dataset_args.random_seed=${item.random_seed} ${global_options}
    deps:
      - experiments/baseline_${item.experiment}/hpsearch_eval_loss_data_split_seed_${item.random_seed}.jsonl
      - experiments/exp_2_mecla_${item.experiment}/hpsearch_eval_loss_data_split_seed_${item.random_seed}.jsonl
      - datasets/breast_cancer_dataset
    outs:
      - experiments/exp_2_mecla_${item.experiment}/metrics_data_split_seed_${item.random_seed}.jsonl

  exp_3_mecla:
    matrix:
      experiment: ${models}
      random_seed: ${random_seed}
    cmd: python train.py --config experiments/exp_3_mecla_${item.experiment}.yaml --set dataset_args.random_seed=${item.random_seed} ${global_options}
    deps:
      - experiments/baseline_${item.experiment}/hpsearch_eval_loss_data_split_seed_${item.random_seed}.jsonl
      - datasets/breast_cancer_dataset
    outs:
      - experiments/exp_3_mecla_${item.experiment}/metrics_data_split_seed_${item.random_seed}.jsonl

  exp_4_mecla:
    matrix:
      experiment: ${models}
      mecla_amplification_factor: [0.001, 0.01, 0.1, 1.0, 2.0, 5.0, 10.0]
    cmd: python train.py --config experiments/exp_4_mecla_${item.experiment}.yaml --set trainer_args.mecla_amplification_factor=${item.mecla_amplification_factor} ${global_options}
    deps:
      - experiments/baseline_${item.experiment}/hpsearch_eval_loss_data_split_seed_3.jsonl
      - datasets/breast_cancer_dataset

  exp_5_mecla:
    matrix:
      experiment: ${models}
      random_seed: ${random_seed}
    cmd: python train.py --config experiments/exp_5_mecla_${item.experiment}.yaml --set dataset_args.random_seed=${item.random_seed} --set trainer_args.mecla_amplification_factor=5 ${global_options}
    deps:
      - experiments/baseline_${item.experiment}/hpsearch_eval_loss_data_split_seed_${item.random_seed}.jsonl
      - datasets/breast_cancer_dataset
    outs:
      - experiments/exp_5_mecla_${item.experiment}/metrics_data_split_seed_${item.random_seed}.jsonl

  nestedclinbr_mmbert_baseline:
    matrix:
      random_seed: ${random_seed}
    cmd: python train.py --config experiments/nestedclinbr_mmbert_baseline.yaml ${global_options}
    deps:
      - datasets/nested_clin_dataset

  nestedclinbr_mmbert_mecla:
    matrix:
      random_seed: ${random_seed}
    cmd: python train.py --config experiments/nestedclinbr_mmbert_mecla.yaml ${global_options}
    deps:
      - datasets/nested_clin_dataset

  exp_6_mecla:
    matrix:
      experiment: ${models}
      random_seed: ${random_seed}
    cmd: python train.py --config experiments/exp_6_mecla_${item.experiment}.yaml --set dataset_args.random_seed=${item.random_seed} ${global_options}
    outs:
      - experiments/exp_6_mecla_${item.experiment}/metrics_data_split_seed_${item.random_seed}.jsonl