vars:
  - repetitions: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  - global_options: ""
  - models:
      - mmbert
      - biobertpt
      - modernbert

stages:
  baseline_hpsearch:
    matrix:
      experiment: ${models}
    cmd: python hpsearch.py --config experiments/baseline_${item.experiment}.yaml ${global_options}
    deps:
      - datasets/breast_cancer_dataset
      - hpsearch.py
    outs:
      - experiments/baseline_${item.experiment}/hpsearch_eval_loss.jsonl

  baseline:
    matrix:
      experiment: ${models}
      repetitions: ${repetitions}
    cmd: python train.py --config experiments/baseline_${item.experiment}.yaml ${global_options}
    deps:
      - experiments/baseline_${item.experiment}/hpsearch_eval_loss.jsonl
      - datasets/breast_cancer_dataset
    outs:
      - experiments/baseline_${item.experiment}/metrics.jsonl

  exp_1_mecla_hpsearch:
    matrix:
      experiment: ${models}
    cmd: python hpsearch.py --config experiments/exp_1_mecla_${item.experiment}.yaml ${global_options}
    deps:
      - experiments/baseline_${item.experiment}/hpsearch_eval_loss.jsonl
      - datasets/breast_cancer_dataset
    outs:
      - experiments/exp_1_mecla_${item.experiment}/hpsearch_eval_macro_pr_auc.jsonl

  exp_1_mecla:
    matrix:
      experiment: ${models}
      repetitions: ${repetitions}
    cmd: python train.py --config experiments/exp_1_mecla_${item.experiment}.yaml ${global_options}
    deps:
      - experiments/baseline_${item.experiment}/hpsearch_eval_loss.jsonl
      - experiments/exp_1_mecla_${item.experiment}/hpsearch_eval_macro_pr_auc.jsonl
      - datasets/breast_cancer_dataset
    outs:
      - experiments/exp_1_mecla_${item.experiment}/metrics.jsonl

  exp_2_mecla_hpsearch:
    matrix:
      experiment: ${models}
    cmd: python hpsearch.py --config experiments/exp_2_mecla_${item.experiment}.yaml ${global_options}
    deps:
      - experiments/baseline_${item.experiment}/hpsearch_eval_loss.jsonl
      - datasets/breast_cancer_dataset
    outs:
      - experiments/exp_2_mecla_${item.experiment}/hpsearch_eval_macro_pr_auc.jsonl

  exp_2_mecla:
    matrix:
      experiment: ${models}
      repetitions: ${repetitions}
    cmd: python train.py --config experiments/exp_2_mecla_${item.experiment}.yaml ${global_options}
    deps:
      - experiments/baseline_${item.experiment}/hpsearch_eval_loss.jsonl
      - experiments/exp_2_mecla_${item.experiment}/hpsearch_eval_macro_pr_auc.jsonl
      - datasets/breast_cancer_dataset
    outs:
      - experiments/exp_2_mecla_${item.experiment}/metrics.jsonl